canvaspath/app/urls.py
from django.conf.urls import include, url
from .views import *
from django.views.generic import TemplateView

app_name = 'app'

urlpatterns = [
    url('^$', login),
]

canvaspath/canvaspath/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from app.views import *
from app.administrator import *
from app.student import *
from app.professor import *

urlpatterns = [
    url('^$', login),
    url(r'^change_pw/$', change_pw),
    url(r'^admin/', admin.site.urls),
    url(r'^administrator/show_students/$', show_students),
    url(r'^administrator/import_students/$', import_students),
    url(r'^administrator/show_professors/$', show_professors),
    url(r'^administrator/import_professors/$', import_professors),
    url(r'^administrator/course_management/$', CourseList.as_view()),
    url(r'^administrator/course_management/new/$', CourseCreate.as_view()),
    url(r'^administrator/course_management/update/(?P<id>.+)/$', CourseUpdate.as_view()),
    url(r'^administrator/course_management/delete/(?P<id>.+)/$', CourseDelete.as_view()),
    url(r'^administrator/section_management/(?P<id>.+)/$', SectionList.as_view()),
    url(r'^administrator/new_section/(?P<id>.+)/$', SectionCreate.as_view()),
    url(r'^administrator/section_prof_team/(?P<id>.+)/$', section_prof_team),
]

urlpatterns += [
    url(r'^student/change_info/$', change_info),
    url(r'^student/show_courses/$', student_courses),
    url(r'^student/choose_course/(?P<id>.+)/$', choose_course),
    url(r'^student/my_courses/$', my_courses),
    url(r'^student/reg_detail/(?P<id>.+)/$', reg_detail),
    url(r'^student/cap_detail/(?P<id>.+)/$', cap_detail),
]

urlpatterns += [
    url(r'^professor/courses/$', professor_courses),
    url(r'^professor/homeworks/(?P<id>.+)/$', homework_list),
    url(r'^professor/homework/new/(?P<id>.+)/$', HomeworkCreate.as_view()),
    url(r'^professor/homework/score/(?P<id>.+)/$', change_homework_score),
    url(r'^professor/exams/(?P<id>.+)/$', exam_list),
    url(r'^professor/exam/new/(?P<id>.+)/$', ExamCreate.as_view()),
    url(r'^professor/exam/score/(?P<id>.+)/$', change_exam_score),
    url(r'^professor/cap/(?P<id>.+)/$', cap_list),
    url(r'^professor/score_sheet/(?P<id>.+)/$', score_sheet),
]

canvaspath/app/models.py
from django.db import models


class Zipcode(models.Model):
    def __str__(self):
        return self.zipcode
    zipcode = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)


#Create your models here.
class Student(models.Model):
    def __str__(self):
        return self.name

    email = models.CharField(max_length=50, null=True)
    password = models.CharField(max_length=300, null=True, default="123456")
    name = models.CharField(max_length=50, null=True)
    age = models.IntegerField(default=0, null=True)
    gender = models.CharField(max_length=2, null=True)
    major = models.CharField(max_length=50, null=True)
    street = models.CharField(max_length=50, null=True)
    phone = models.CharField(max_length=50, null=True)
    # zipcode = models.ForeignKey(Zipcode)
    zipcode = models.CharField(max_length=50, null=True)


class Department(models.Model):
    def __str__(self):
        return self.dept_name
    # id is auto
    dept_head = models.CharField(max_length=50, null=True)
    dept_name = models.CharField(max_length=50, null=True)


class Professor(models.Model):
    email = models.CharField(max_length=50, null=True)
    password = models.CharField(max_length=300, null=True, default="123456")
    name = models.CharField(max_length=50, null=True)
    age = models.IntegerField(default=0, null=True)
    gender = models.CharField(max_length=2, null=True)
    office_address = models.CharField(max_length=50, null=True)
    title = models.CharField(max_length=50, null=True)  # position
    department = models.ForeignKey(Department)


class Administrator(models.Model):
    email = models.CharField(max_length=50, null=True)
    password = models.CharField(max_length=50, null=True, default="123456")


class Prof_teams(models.Model):
    def __str__(self):
        return self.team_name
    team_name = models.CharField(max_length=50, null=True)


class Prof_team_members(models.Model):
    professor = models.ForeignKey(Professor)
    teaching_team_id = models.ForeignKey(Prof_teams)


class Course(models.Model):
    def __str__(self):
        return self.course_name
    course_id = models.CharField(max_length=50, null=True)
    course_name = models.CharField(max_length=50, null=True)
    course_description = models.CharField(max_length=1000, null=True)


class Sections(models.Model):
    def __str__(self):
        return self.section_name
    course_id = models.ForeignKey(Course)
    section_no = models.IntegerField(default=1)
    section_name = models.CharField(max_length=50, null=True)
    TYPE_CHOICE = (
        ('Reg', 'regular'),
        ('Cap', 'capstone')
    )
    section_type = models.CharField(max_length=10, choices=TYPE_CHOICE, default='Reg')
    limit = models.IntegerField(default=50)
    teaching_team_id = models.ForeignKey(Prof_teams, null=True)


class Enrolls(models.Model):
    student = models.ForeignKey(Student)
    section = models.ForeignKey(Sections)


class Homework(models.Model):
    section = models.ForeignKey(Sections)
    hw_no = models.IntegerField(default=1)
    hw_details = models.CharField(max_length=1000, null=True)


class Homework_grades(models.Model):
    student = models.ForeignKey(Student)
    homework = models.ForeignKey(Homework, null=True)
    grades = models.DecimalField(max_digits=4, decimal_places=2, null=False, default=0.00)  # float


class Exams(models.Model):
    section = models.ForeignKey(Sections)
    exam_no = models.IntegerField(default=1)
    exam_details = models.CharField(max_length=1000, null=True)


class Exam_grades(models.Model):
    student = models.ForeignKey(Student)
    exam = models.ForeignKey(Exams)
    grades = models.DecimalField(max_digits=4, decimal_places=2, null=False, default=0.00)  # float


class Capstone_section(models.Model):
    section = models.ForeignKey(Sections)
    project_no = models.IntegerField(default=1)
    sponsor_id = models.ForeignKey(Professor)


class Capstone_Team(models.Model):
    project_no = models.ForeignKey(Capstone_section)


class Capstone_Team_Members(models.Model):
    team = models.ForeignKey(Capstone_Team)
    student = models.ForeignKey(Student)


class Capstone_grades(models.Model):
    team = models.ForeignKey(Capstone_Team)
    grade = models.DecimalField(max_digits=4, decimal_places=2, null=False, default=0.00)  # float


class FinalScore(models.Model):
    section = models.ForeignKey(Sections)
    student = models.ForeignKey(Student)
    grade = models.DecimalField(max_digits=4, decimal_places=2, null=False, default=0.00)  # float

canvaspath/app/templates/app/admin_delete_course.html
{% extends "app/admin_base.html" %}
{% load staticfiles %}
{% load render_table from django_tables2 %}
{% block personal-right %}
   <div class="wrapper wrapper-content ibox-content">
    <form class="text-center" action="" method="post" style="margin-top: 10%;" xmlns="http://www.w3.org/1999/html">{% csrf_token %}
        <h1 style="line-height: 3.5rem;">Are you sure to delete the course named :"<strong>{{ object.course_name }}</strong>"</h1>
        <button class="btn btn-black" style="font-size: 2.9rem;margin-top: 5%;background-color: #ffa62e;width: 15%" id="cancel">cancel</button>
        <input class="btn btn-primary" type="submit" value="sure" style="font-size: 2.9rem;margin-top: 5%;background-color: #ffa62e" />
    </form>
    </div>
{% endblock %}
{% block script %}
{#    <script src={% static "js/jquery.cookie.js"%}></script>#}
    <script type="text/javascript">
        $("#cancel").click(function () {
            window.location.href = "/administrator/course_management/";
            return false;
        })
    </script>
{% endblock %}

canvaspath/app/templates/app/admin_new_section.html
{% extends "app/admin_base.html" %}
{% load staticfiles %}
{% load render_table from django_tables2 %}
<style>
         #save{
            display: block;
            margin:0 30%;
             width: 6%;
        }
        #cke_id_introduction,#cke_id_task{
            display: block;
            margin: 2% 5%;
            width: 90%;
        }
        label{
            display: inline;
        }
        #id_author, #id_permission, #id_name,#id_coursetype{
            height:30px;
        }
        #id_short_introduction{
            display: block;
            margin:2% 3%;
            width: 59%;
{#            margin: 2% 5%;#}
{#            width: 80%;#}
        }
        img{
            height: auto !important; max-width: 100%;
        }
    </style>
{% block personal-right %}
    <div class="wrapper wrapper-content ibox-content">
    <br><br>
        <form action="" method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                <tr style="height: 40px;">
                    <td>{{ form.course_id.label_tag }}</td>
                    <td style="padding-left: 20px">{{ form.course_id }}</td>
                    <td>{{ form.course_id.errors }}</td>
                </tr>
                <tr style="height: 40px;">
                    <td>{{ form.section_name.label_tag }}</td>
                    <td style="padding-left: 20px">{{ form.section_name }}</td>
                    <td>{{ form.section_name.errors }}</td>
                </tr>
                <tr style="height: 40px;">
                    <td>{{ form.section_type.label_tag }}</td>
                    <td style="padding-left: 20px">{{ form.section_type }}</td>
                    <td>{{ form.section_type.errors }}</td>
                </tr>
                <tr style="height: 40px;">
                    <td>{{ form.limit.label_tag }}</td>
                    <td style="padding-left: 20px">{{ form.limit }}</td>
                    <td>{{ form.limit.errors }}</td>
                </tr>
            </table>
        <input id="save" class="btn btn-primary " type="submit" value="save" style="background-color: #ffa62e"/>
        </form>
    <a class="btn btn-primary" style="text-align: center;background-color: #ffa62e" href="/administrator/section_management/{{ id }}/" >back</a>
    </div>
{% endblock %}
{% block script %}
    <script src={% static "js/select2.full.min.js"%}></script>
    <link href={% static "css/select2.min.css" %} rel="stylesheet">
    <script>
        $("#id_course_id option[value='{{ id }}']").attr("selected", true);
        $("#id_course_id").attr("disabled", "disabled");
        $("#save").click(function () {
           $("#id_course_id").attr("disabled", false);
        });
    </script>
{% endblock %}

canvaspath/app/templates/app/admin_update_course.html
{% extends "app/admin_base.html" %}
{% load staticfiles %}
{% load render_table from django_tables2 %}
<style>
         #save{
            display: block;
            margin:0 30%;
             width: 6%;
        }
        #cke_id_introduction,#cke_id_task{
            display: block;
            margin: 2% 5%;
            width: 90%;
        }
        label{
            display: inline;
        }
        #id_author, #id_permission, #id_name,#id_coursetype{
            height:30px;
        }
        #id_short_introduction{
            display: block;
            margin:2% 3%;
            width: 59%;
{#            margin: 2% 5%;#}
{#            width: 80%;#}
        }
        img{
            height: auto !important; max-width: 100%;
        }
    </style>
{% block personal-right %}
    <div class="wrapper wrapper-content ibox-content">
    <br><br>
        <form action="" method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                <tr style="height: 40px;">
                    <td>{{ form.course_id.label_tag }}</td>
                    <td style="padding-left: 20px">{{ form.course_id }}</td>
                    <td>{{ form.course_id.errors }}</td>
                </tr>
                <tr style="height: 40px;">
                    <td>{{ form.course_name.label_tag }}</td>
                    <td style="padding-left: 20px">{{ form.course_name }}</td>
                    <td>{{ form.course_name.errors }}</td>
                </tr>
                <tr style="height: 200px;">
                    <td>{{ form.course_description.label_tag }}</td>
                    <td style="padding-left: 20px">{{ form.course_description }}</td>
                    <td>{{ form.course_description.errors }}</td>
                </tr>
            </table>
        <input id="save" class="btn btn-primary " type="submit" value="save" style="background-color: #ffa62e"/>
        </form>
    <a class="btn btn-primary" style="text-align: center;background-color: #ffa62e" href="/administrator/course_management/" >back</a>
    </div>
{% endblock %}

canvaspath/app/templates/app/administrator_professor_management.html
{% extends "app/admin_base.html" %}
{% load staticfiles %}
{% load render_table from django_tables2 %}
{% block personal-right %}
    <div >
            <legend>Import Professors:</legend>
            <form enctype="multipart/form-data" method="post" id="net">
                {% csrf_token %}
                <input type="file" id="myfile" name="myfile" style="height: 32px;font-size: 1.4rem;"/>
                <br><br>
                <button type="button" id="upload" class="btn met2" style="width: 82px; margin:auto 4% auto auto; color: #FFFFFF">upload</button>
            </form>
{#           <button id="muban"  class="btn btn-primary" onclick="window.open('{% static 'ScratchJR/jr_import_students.xlsx' %}','_self');" style="width: 82px;margin:1% auto auto auto">模版下载</button>#}
 </div>
    {% if professor_table %}
        <div class="row">
            <div class="col-lg-6">
                <div class="ibox">
                    <div class="ibox-content">
                        {% render_table professor_table "app/table.html" %}
                    </div>
                </div>
            </div>
        </div>

            {% endif %}
{% endblock %}
{% block script %}
    <script src={% static "js/bootstrap-3.1.1.min.js" %}></script>
    <script>
        $("#upload").click(function () {
            var myfilecontent=document.getElementById('myfile').value;
            if(myfilecontent=="")
            {
                alert('no file!');
                return false;
            }
            else {
                var formData = new FormData();
                formData.append("myfile", document.getElementById("myfile").files[0]);
                formData.append("csrfmiddlewaretoken", document.getElementsByName("csrfmiddlewaretoken")[0].value);
                $.ajax({
                    url: "/administrator/import_professors/",
                    type: "POST",
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function (data) {
                        alert(data);
                    },
                    error: function () {
                        alert("failed to upload！");
                    }
                });
            }
    });
    </script>
{% endblock %}

canvaspath/app/templates/app/change_pw.html
{% extends "app/base.html" %}
{% load staticfiles %}
{% block content %}
    <!-- breadcrumbs -->
	<div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
				<li><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>Home</a></li>
				<li class="active">Change PW</li>
			</ol>
		</div>
	</div>
<!-- //breadcrumbs -->
<!-- register -->
    {% if not no_user %}
	<div class="register">
		<div class="container">
			<h3 class="animated wow zoomIn" data-wow-delay=".5s" >CHANGE PASSWORD</h3>
			<p class="est animated wow zoomIn" data-wow-delay=".5s">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
				deserunt mollit anim id est laborum.</p>
			<div class="login-form-grids">
                <div class="animated wow slideInUp" data-wow-delay=".5s">
                    {% csrf_token %}
                    <div>
                        <label for="username">Email:</label>
                        <input id="username" type="text" readonly="readonly" value="{{ username }}">
                    </div>
					<div>
                        <label for="pre_password">password:</label>
                        <input id="pre_password" type="password" required="required" ><small id="pre_pwd_error" style="color: darkred;">password error</small>
                    </div>
                    <div>
                        <label for="new_password">new password</label>
                        <input id="new_password" type="password" required="required" ><small id="pwd_error" style="color: darkred;"></small>
                    </div>
                    <div>
                        <label for="password_confirm">confirm:</label>
                        <input id="password_confirm" type="password" required="required" ><small id="pwd_confirm_error" style="color: darkred;">does not match</small>
                    </div>

                    <button id="submit_change">Change</button>
{#					<input id="submit_register" type="submit" value="Register">#}
{#				</form>#}
			</div>
{#			<div class="register-home animated wow slideInUp" data-wow-delay=".5s">#}
{#				<a href="/">Home</a>#}
			</div>
		</div>
	</div>
    {% endif %}
<!-- //register -->
{%  endblock %}

{% block script %}
    <script  src="{% static "js/selects.js" %}"></script>
    <script>

    $(document).ready(function () {

        $("#pre_pwd_error").hide();
        $("#pwd_error").hide();
        $("#pwd_confirm_error").hide();

    });


    $("#submit_change").click(function () {
        var pre_password = $("#pre_password").val();
        var new_password = $("#new_password").val();
        var password_confirm = $("#password_confirm").val();
        var csrftokens = $("input[name='csrfmiddlewaretoken']").val();
        if(pre_password == '' || new_password == '' || password_confirm == ''){
             alert("请填写完整信息！");
            return
        }
        var data = {
            'csrfmiddlewaretoken': csrftokens,
            'pre_password': pre_password,
            'new_password': new_password,
            'password_confirm': password_confirm
        };
{#        alert(username);#}
        $.ajax({
            url: '/change_pw/',
            type: 'POST',
            dataType:"json",
            data: data,
            success: function (data) {
                if(data['result'] == 'pre_pwd_error'){
                    $("#pre_pwd_error").show();
                    $("#pwd_error").hide();
                    $("#pwd_confirm_error").hide();
                }
                else if(data['result'] == 'pwd_confirm_error'){
                    $("#pwd_confirm_error").show();
                    $("#pre_pwd_error").hide();
                    $("#pwd_error").hide();
                }
                else if(data['result'] == 'success'){
                    alert("success");
                    setTimeout(window.location.href = '/', 3);
                }
            },
            error: function () {
                alert("failed");
            }
        });
    });

    </script>
{% endblock %}

canvaspath/app/templates/app/professor_courses.html
{% extends "app/professor_base.html" %}
{% load staticfiles %}
{% load render_table from django_tables2 %}
{% block personal-right %}
    <br><br>

    {% if section_table %}
        <div class="row">
            <div class="col-lg-6">
                <div class="ibox">
                    <div class="ibox-content">
                        {% render_table section_table "app/table.html" %}
                    </div>
                </div>
            </div>
        </div>

            {% endif %}
{% endblock %}

canvaspath/app/templates/app/professor_homework_score.html
{% extends "app/professor_base.html" %}
{% load staticfiles %}
{% load render_table from django_tables2 %}
{% block personal-right %}
    <br><br>
    <h4>HOMEWORK SCORE</h4>
    {% csrf_token %}
    <br><br>
    <div id="change_score">
        <label for="score">input score:</label>
        <input id="score" type="text">
        <input class="btn btn btn-primary" type="submit" value="submit" style="margin-top: 15px; background-color: #ffb81c" onclick="change()">

    </div>

    {% if grade_table %}
        <div class="row">
            <div class="col-lg-6">
                <div class="ibox">
                    <div class="ibox-content">
                        {% render_table grade_table "app/table.html" %}
                    </div>
                </div>
            </div>
        </div>

            {% endif %}
{% endblock %}
{% block script %}
    <script>
    current_id = 0;
    $(document).ready(function () {
       $("#change_score").hide();
    });
    function change_score(pk) {
        current_id = pk;
        $("#change_score").show();
        return false;
    }
    function change() {
        var csrftokens = $("input[name='csrfmiddlewaretoken']").val();
        var score = $("#score").val();
            $.ajax({
                url: '/professor/homework/score/{{ id }}/',
                type: 'POST',
                dataType:'json',
                data: {
                    'csrfmiddlewaretoken': csrftokens,
                    'current_id':current_id,
                    'score': score
                },
                success: function (data) {
                    $("#change_score").hide();
                    alert(data);
                    window.location.href = '/professor/homework/score/{{ id }}/'
                    },
                error: function () {
                    alert('failed to change');
                }
        })
    }
    </script>
{% endblock %}

canvaspath/app/templates/app/professor_new_exam.html
{% extends "app/professor_base.html" %}
{% load staticfiles %}
{% load render_table from django_tables2 %}
<style>
         #save{
            display: block;
            margin:0 30%;
             width: 6%;
        }
        #cke_id_introduction,#cke_id_task{
            display: block;
            margin: 2% 5%;
            width: 90%;
        }
        label{
            display: inline;
        }
        #id_author, #id_permission, #id_name,#id_coursetype{
            height:30px;
        }
        #id_short_introduction{
            display: block;
            margin:2% 3%;
            width: 59%;
{#            margin: 2% 5%;#}
{#            width: 80%;#}
        }
        img{
            height: auto !important; max-width: 100%;
        }
    </style>
{% block personal-right %}
    <div class="wrapper wrapper-content ibox-content">
    <br><br>
        <form action="" method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                <tr style="height: 40px;">
                    <td>{{ form.section.label_tag }}</td>
                    <td style="padding-left: 20px">{{ form.section }}</td>
                    <td>{{ form.section.errors }}</td>
                </tr>
                <tr style="height: 40px;">
                    <td>{{ form.exam_details.label_tag }}</td>
                    <td style="padding-left: 20px">{{ form.exam_details }}</td>
                    <td>{{ form.exam_details.errors }}</td>
                </tr>

            </table>
        <input id="save" class="btn btn-primary " type="submit" value="save" style="background-color: #ffa62e"/>
        </form>
    <a class="btn btn-primary" style="text-align: center;background-color: #ffa62e" href="/professor/exams/{{ id }}/" >back</a>
    </div>
{% endblock %}
{% block script %}
    <script src={% static "js/select2.full.min.js"%}></script>
    <link href={% static "css/select2.min.css" %} rel="stylesheet">
    <script>
        $("#id_section option[value='{{ id }}']").attr("selected", true);
        $("#id_section").attr("disabled", "disabled");
        $("#save").click(function () {
           $("#id_section").attr("disabled", false);
        });
    </script>
{% endblock %}

canvaspath/app/templates/app/professor_new_homework.html
{% extends "app/professor_base.html" %}
{% load staticfiles %}
{% load render_table from django_tables2 %}
<style>
         #save{
            display: block;
            margin:0 30%;
             width: 6%;
        }
        #cke_id_introduction,#cke_id_task{
            display: block;
            margin: 2% 5%;
            width: 90%;
        }
        label{
            display: inline;
        }
        #id_author, #id_permission, #id_name,#id_coursetype{
            height:30px;
        }
        #id_short_introduction{
            display: block;
            margin:2% 3%;
            width: 59%;
{#            margin: 2% 5%;#}
{#            width: 80%;#}
        }
        img{
            height: auto !important; max-width: 100%;
        }
    </style>
{% block personal-right %}
    <div class="wrapper wrapper-content ibox-content">
    <br><br>
        <form action="" method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            <table>
                <tr style="height: 40px;">
                    <td>{{ form.section.label_tag }}</td>
                    <td style="padding-left: 20px">{{ form.section }}</td>
                    <td>{{ form.section.errors }}</td>
                </tr>
                <tr style="height: 40px;">
                    <td>{{ form.hw_details.label_tag }}</td>
                    <td style="padding-left: 20px">{{ form.hw_details }}</td>
                    <td>{{ form.hw_details.errors }}</td>
                </tr>

            </table>
        <input id="save" class="btn btn-primary " type="submit" value="save" style="background-color: #ffa62e"/>
        </form>
    <a class="btn btn-primary" style="text-align: center;background-color: #ffa62e" href="/professor/homeworks/{{ id }}/" >back</a>
    </div>
{% endblock %}
{% block script %}
    <script src={% static "js/select2.full.min.js"%}></script>
    <link href={% static "css/select2.min.css" %} rel="stylesheet">
    <script>
        $("#id_section option[value='{{ id }}']").attr("selected", true);
        $("#id_section").attr("disabled", "disabled");
        $("#save").click(function () {
           $("#id_section").attr("disabled", false);
        });
    </script>
{% endblock %}

canvaspath/app/templates/app/student_base.html
{% extends "app/base.html" %}
{% load staticfiles %}
{% block content %}
    <div class="container">
			<div class="col-md-4 products-left">
				<div class="categories animated wow slideInUp" data-wow-delay=".5s">
					<h3>Categories</h3>
					<ul class="cate">
						<li><a href="/student/show_courses/">choose course</a></li>
                        <li><a href="/student/my_courses/">my courses</a></li>
						<li><a href="/student/change_info/">change info</a></li>
					</ul>
				</div>
            </div>
    {% block personal-right %}
    {% endblock %}
    </div>

{% endblock %}

canvaspath/app/templates/app/student_choose_course.html
{% extends "app/student_base.html" %}
{% load staticfiles %}
{% load render_table from django_tables2 %}
{% block personal-right %}
    <br><br>
    <form action="/student/show_courses/">

        <div class="ibox-content m-b-sm border-bottom" style="overflow: hidden">
        <div class="flexpos" >
            <div class="form-inline">
                <input type="text" id="search" value="{{ course_name }}" placeholder="course_name" name="course_name" >
            <input type="submit" class="btn btn-primary" style="background-color: orange;border-color: orange;" value="search">
        </div>
    </div>
    </form>
    {% if course_table %}
        <div class="row">
            <div class="col-lg-6">
                <div class="ibox">
                    <div class="ibox-content">
                        {% render_table course_table "app/table.html" %}
                    </div>
                </div>
            </div>
        </div>

            {% endif %}
{% endblock %}

canvaspath/app/templates/app/student_my_courses.html
{% extends "app/student_base.html" %}
{% load staticfiles %}
{% load render_table from django_tables2 %}
{% block personal-right %}
    <br><br>

    {% if section_table %}
        <div class="row">
            <div class="col-lg-6">
                <div class="ibox">
                    <div class="ibox-content">
                        {% render_table section_table "app/table.html" %}
                    </div>
                </div>
            </div>
        </div>

            {% endif %}
{% endblock %}